### PR TITLE
Fix defaults for postgres config so that local config override is not needed

### LINKED ISSUE #99: Postgres syncer has incorrect local defaults
Attempting to sync postgres with a config file that doesn't include `local` will fallback to environment variables that are not valid:

```bash
[DEBUG] 2023/09/27 16:42:34 github.com/uselagoon/lagoon-sync/utils.LogDebugInfo:logs.go:62 Config that will be used for sync {
  "Config": {
    "DbHostname": "${POSTGRES_HOST:-postgres}",
    "DbUsername": "${POSTGRES_USERNAME:-drupal}",
    "DbPassword": "${POSTGRES_PASSWORD:-drupal}",
    "DbPort": "${POSTGRES_PORT:-5432}",
    "DbDatabase": "${POSTGRES_DATABASE:-drupal}",
    "ExcludeTable": null,
    "ExcludeTableData": null,
    "OutputDirectory": ""
  },
  "LocalOverrides": {
    "Config": {
      "DbHostname": "$AMAZEEIO_DB_HOST",
      "DbUsername": "$AMAZEEIO_DB_USERNAME",
      "DbPassword": "$AMAZEEIO_DB_PASSWORD",
      "DbPort": "$AMAZEEIO_DB_PORT",
      "DbDatabase": "$POSTGRES_DATABASE",
      "ExcludeTable": null,
      "ExcludeTableData": null,
      "OutputDirectory": ""
    }
  },
  "TransferId": ""
}
```

This causes the sync to fail on the target environment.

### PR DESCRIPTION
**Pull request by rocketeerbkw**
closes #99

### CODE REVIEW

**Review by tobybellwood — COMMENTED** [review]
Should we not use the non-Drupal defaults here? https://github.com/uselagoon/lagoon-images/blob/main/images/postgres/15.Dockerfile#L35

**Comment by rocketeerbkw** [comment]
We use drupal as the default for mariadb, so I'd say keep them in sync either way https://github.com/uselagoon/lagoon-sync/blob/main/synchers/mariadb.go#L43

**Comment by tobybellwood** [comment]
> We use drupal as the default for mariadb, so I'd say keep them in sync either way https://github.com/uselagoon/lagoon-sync/blob/main/synchers/mariadb.go#L43

Good point, that's an oversight. Agree to keep them in sync then, but should work out a better way for both.

**Comment by bomoko** [comment]
@rocketeerbkw and @tobybellwood - this seems good to me, let me know if you're happy for me to merge.

**Review by tobybellwood — APPROVED** [review]
Approved - we'll replace the "drupal" defaults in a subsequent PR

**Pull request merged**
